## tomcat 配置
server:
  port: 9005

## Spring 配置
spring:
  jmx:
    ### 关闭JMX监控配置
    enable: false
  ## redis 配置，以 spring.redis 为前缀
  redis:
    ### 数据库索引（默认为0）
    database: 0
    ### 服务器地址
    host: 127.0.0.1
    ### 端口
    port: 6379
    ### 密码（默认为空，为空时不设置该属性）
#    password:
    ### 超时时间（毫秒）
    timeout: 30000
    ### 建议使用 lettuce 可以换成 jedis，spring 默认集成了 lettuce
    client-type: lettuce
    ##  如果使用jedis客户端，则下面定义的内容需要将 lettuce 换成 jedis
    lettuce:
      pool:
        ### 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        ### 最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -2
        ### 最大空闲连接数
        max-idle: 10
        ### 最小空闲连接
        min-idle: 0



  ## 配置中心配置 tomcat 线程池核心参数
  dynamic:
    tp:
      tomcatTp:
        corePoolSize: 100
        maximumPoolSize: 400
        keepAliveTime: 60